/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.82
 * Generated at: 2024-06-10 12:34:35 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.projecttest;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class contact_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"ko\">\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\r\n");
      out.write("<title>연락처 관리</title>\r\n");
      out.write("<link href=\"https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css\" rel=\"stylesheet\" integrity=\"sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH\" crossorigin=\"anonymous\">\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"css/contact2.css\">\r\n");
      out.write("</head>\r\n");
      out.write("<body class=\"bg-light\">\r\n");
      out.write("    <div class=\"container mt-5\">\r\n");
      out.write("        <!-- Login Section -->\r\n");
      out.write("        <div id=\"loginSection\" class=\"row justify-content-center\">\r\n");
      out.write("            <div class=\"col-md-6\">\r\n");
      out.write("                <div class=\"card shadow-sm\">\r\n");
      out.write("                    <div class=\"card-body\">\r\n");
      out.write("                        <h2 class=\"mb-4 text-center\">로그인</h2>\r\n");
      out.write("                        <form id=\"loginForm\" action=\"contactControlTest?action=login\" method=\"post\">\r\n");
      out.write("                            <div class=\"mb-3\">\r\n");
      out.write("                                <label for=\"user_id\" class=\"form-label\">아이디</label> \r\n");
      out.write("                                <input type=\"text\" id=\"user_id\" name=\"user_id\" class=\"form-control\" required>\r\n");
      out.write("                            </div>\r\n");
      out.write("                            <div class=\"mb-3\">\r\n");
      out.write("                                <label for=\"password\" class=\"form-label\">비밀번호</label> \r\n");
      out.write("                                <input type=\"password\" id=\"password\" name=\"password\" class=\"form-control\" required>\r\n");
      out.write("                            </div>\r\n");
      out.write("                            <button type=\"submit\" class=\"btn btn-primary w-100\">로그인</button>\r\n");
      out.write("                        </form>\r\n");
      out.write("                        <p class=\"mt-3 text-center\">\r\n");
      out.write("                            계정이 없으신가요? <a href=\"#\" onclick=\"showRegister()\">계정 만들기</a>\r\n");
      out.write("                        </p>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("        <!-- Register Section -->\r\n");
      out.write("        <div id=\"registerSection\" class=\"row justify-content-center hidden\">\r\n");
      out.write("            <div class=\"col-md-6\">\r\n");
      out.write("                <div class=\"card shadow-sm\">\r\n");
      out.write("                    <div class=\"card-body\">\r\n");
      out.write("                        <h2 class=\"mb-4 text-center\">계정 생성</h2>\r\n");
      out.write("                        <form id=\"registerForm\" action=\"contactControlTest?action=register\" method=\"post\">\r\n");
      out.write("                            <div class=\"mb-3\">\r\n");
      out.write("                                <label for=\"regUser_id\" class=\"form-label\">아이디</label> \r\n");
      out.write("                                <input type=\"text\" id=\"regUser_id\" name=\"user_id\" class=\"form-control\" required>\r\n");
      out.write("                            </div>\r\n");
      out.write("                            <div class=\"mb-3\">\r\n");
      out.write("                                <label for=\"regPassword\" class=\"form-label\">비밀번호</label> \r\n");
      out.write("                                <input type=\"password\" id=\"regPassword\" name=\"password\" class=\"form-control\" required>\r\n");
      out.write("                            </div>\r\n");
      out.write("                            <div class=\"mb-3\">\r\n");
      out.write("                                <label for=\"regName\" class=\"form-label\">이름</label> \r\n");
      out.write("                                <input type=\"text\" id=\"regName\" name=\"user_name\" class=\"form-control\" required>\r\n");
      out.write("                            </div>\r\n");
      out.write("                            <button type=\"submit\" class=\"btn btn-primary w-100\">확인</button>\r\n");
      out.write("                        </form>\r\n");
      out.write("                        <p class=\"mt-3 text-center\">\r\n");
      out.write("                            계정이 이미 있으신가요? <a href=\"#\" onclick=\"showLogin()\">로그인하러 가기</a>\r\n");
      out.write("                        </p>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("        <!-- Contact Management Section -->\r\n");
      out.write("        <div id=\"contactSection\" class=\"hidden\">\r\n");
      out.write("            <div class=\"d-flex justify-content-between align-items-center mb-3\">\r\n");
      out.write("                <h2 id=\"contactHeader\">연락처</h2>\r\n");
      out.write("                <button class=\"btn btn-danger\" onclick=\"logout()\">로그아웃</button>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"mb-3\">\r\n");
      out.write("                <input type=\"text\" id=\"searchInput\" class=\"form-control\" placeholder=\"검색\">\r\n");
      out.write("            </div>\r\n");
      out.write("            <table class=\"table table-striped table-hover table-bordered\">\r\n");
      out.write("                <thead class=\"table-dark\">\r\n");
      out.write("                    <tr>\r\n");
      out.write("                        <th>이름</th>\r\n");
      out.write("                        <th>전화번호</th>\r\n");
      out.write("                        <th>주소</th>\r\n");
      out.write("                        <th>구분</th>\r\n");
      out.write("                        <th class=\"action-header\">\r\n");
      out.write("                            <button class=\"btn btn-primary btn-sm\" onclick=\"showAddContactModal()\">추가</button>\r\n");
      out.write("                        </th>\r\n");
      out.write("                    </tr>\r\n");
      out.write("                </thead>\r\n");
      out.write("                <tbody id=\"contactsBody\">\r\n");
      out.write("                    <!-- Contacts will be populated here -->\r\n");
      out.write("                </tbody>\r\n");
      out.write("            </table>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("\r\n");
      out.write("    <!-- Add Contact Modal -->\r\n");
      out.write("    <div class=\"modal fade\" id=\"addContactModal\" tabindex=\"-1\" aria-labelledby=\"addContactModalLabel\" aria-hidden=\"true\">\r\n");
      out.write("        <div class=\"modal-dialog\">\r\n");
      out.write("            <div class=\"modal-content\">\r\n");
      out.write("                <div class=\"modal-header\">\r\n");
      out.write("                    <h5 class=\"modal-title\" id=\"addContactModalLabel\">연락처 추가</h5>\r\n");
      out.write("                    <button type=\"button\" class=\"btn-close\" data-bs-dismiss=\"modal\" aria-label=\"Close\"></button>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"modal-body\">\r\n");
      out.write("                    <form id=\"addContactForm\" action=\"contactControlTest?action=insertContact\" method=\"post\">\r\n");
      out.write("                        <div class=\"mb-3\">\r\n");
      out.write("                            <label for=\"addName\" class=\"form-label\">이름</label> \r\n");
      out.write("                            <input type=\"text\" id=\"addName\" name=\"name\" class=\"form-control\" required>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"mb-3\">\r\n");
      out.write("                            <label for=\"addPhone\" class=\"form-label\">전화번호</label> \r\n");
      out.write("                            <input type=\"text\" id=\"addPhone\" name=\"phone_number\" class=\"form-control\" maxlength=\"11\" required>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"mb-3\">\r\n");
      out.write("                            <label for=\"addAddress\" class=\"form-label\">주소</label> \r\n");
      out.write("                            <input type=\"text\" id=\"addAddress\" name=\"address\" class=\"form-control\" required>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"mb-3\">\r\n");
      out.write("                            <label for=\"addCategory\" class=\"form-label\">구분</label> \r\n");
      out.write("                            <select id=\"addCategory\" name=\"gubun_name\" class=\"form-control\" required>\r\n");
      out.write("                                <option value=\"가족\">가족</option>\r\n");
      out.write("                                <option value=\"친구\">친구</option>\r\n");
      out.write("                                <option value=\"회사\">회사</option>\r\n");
      out.write("                                <option value=\"기타\">기타</option>\r\n");
      out.write("                            </select>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <button type=\"submit\" class=\"btn btn-primary\">추가</button>\r\n");
      out.write("                    </form>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("\r\n");
      out.write("    <!-- Edit Contact Modal -->\r\n");
      out.write("    <div class=\"modal fade\" id=\"editContactModal\" tabindex=\"-1\" aria-labelledby=\"editContactModalLabel\" aria-hidden=\"true\">\r\n");
      out.write("        <div class=\"modal-dialog\">\r\n");
      out.write("            <div class=\"modal-content\">\r\n");
      out.write("                <div class=\"modal-header\">\r\n");
      out.write("                    <h5 class=\"modal-title\" id=\"editContactModalLabel\">연락처 수정</h5>\r\n");
      out.write("                    <button type=\"button\" class=\"btn-close\" data-bs-dismiss=\"modal\" aria-label=\"Close\"></button>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"modal-body\">\r\n");
      out.write("                    <form id=\"editContactForm\" action=\"contactControlTest?action=updateContact\" method=\"post\">\r\n");
      out.write("                        <input type=\"hidden\" id=\"editId\" name=\"contact_id\">\r\n");
      out.write("                        <div class=\"mb-3\">\r\n");
      out.write("                            <label for=\"editName\" class=\"form-label\">이름</label> \r\n");
      out.write("                            <input type=\"text\" id=\"editName\" name=\"name\" class=\"form-control\" required>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"mb-3\">\r\n");
      out.write("                            <label for=\"editPhone\" class=\"form-label\">전화번호</label> \r\n");
      out.write("                            <input type=\"text\" id=\"editPhone\" name=\"phone_number\" class=\"form-control\" maxlength=\"11\" required>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"mb-3\">\r\n");
      out.write("                            <label for=\"editAddress\" class=\"form-label\">주소</label> \r\n");
      out.write("                            <input type=\"text\" id=\"editAddress\" name=\"address\" class=\"form-control\" required>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"mb-3\">\r\n");
      out.write("                            <label for=\"editCategory\" class=\"form-label\">구분</label> \r\n");
      out.write("                            <select id=\"editCategory\" name=\"gubun_name\" class=\"form-control\" required>\r\n");
      out.write("                                <option value=\"가족\">가족</option>\r\n");
      out.write("                                <option value=\"친구\">친구</option>\r\n");
      out.write("                                <option value=\"회사\">회사</option>\r\n");
      out.write("                                <option value=\"기타\">기타</option>\r\n");
      out.write("                            </select>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <button type=\"submit\" class=\"btn btn-primary\">수정</button>\r\n");
      out.write("                    </form>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("\r\n");
      out.write("    <script src=\"https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js\" integrity=\"sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz\" crossorigin=\"anonymous\"></script>\r\n");
      out.write("    <script type=\"text/javascript\" src=\"js/contact.js\"></script>\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
